### ISSUE TITLE
Trying to follow the getting started guide

### ISSUE THREAD

**Issue by murugaratham** [pepaar/typescript-webpack-react-redux-boilerplate#16] opened 2016-12-06 02:17 UTC
Hi Petar,

I tried the following:

- run npm install to download dependencies
- run npm start to build and start webpack-dev-server
- open http://localhost:3333/

But i am getting the following message:

`error TS2322: Type '{}' is not assignable to type 'string'`

My environments are:

$ node -v
v6.9.1

$ npm -v
3.10.8

**Comment by pepaar** [comment] 2016-12-21 22:47
The issue is fixed with #17

**Closed as completed by pepaar** 2016-12-21 22:47 UTC
